const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2349078437844",
    mode: process.env.MODE || "private",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "false",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "false",
    autoReact: process.env.AUTO_REACT === "false",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0FRdkJ1RmcxN3M1cVRjUFU2TFR6Y0RucFZxMkwvL3ZHU1J1c1ZpSU4yYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUE0WklENVlUVTdHMkkwU2VNVmlUbXIyandEaldmbWxGVFVVRXdISnVHTT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJTmVxZGw0WTEzL2dLODQzZVdJb2hRV2hWbzVIbHRDSXNiUDF6QmVtZjNzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTK0lQL0JCbHd4WnFDWnVleFhwdkdxK1h6bW5sMWpobnBzenk5YWpTbDFzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdBemxoZHo5ZVlqOWMxeVB3dVVMbGRCNHZQKzV6cHhLT1c1V2VUNVpTWHM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Imdoa01MWVJNdXpuTG1LcVM0UHFqSXE2RVdJLzE5eDNOcW90bWZVTndyaXc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0hWejM2RGxvcDBTbXJPNVpkT3V3WGY0ZmI2MlNObmM5Q3JsbUJmZVJtdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMmJacjVJOW9VamxnblMzOE5QNGVQeGpSbkhJTUZiUlFaU001a3kzN3EzMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ii9TNWhVaE11S1JZTENYbGZuQlNKM2VXL1hVdzM1T3NqSnY1Y2xtWlhVK2FjQW1xNk1MdmNvNWV6d2FzSDJueEJvYVUzdG5PcjdGcXZkcElEU0oxMURnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQ1LCJhZHZTZWNyZXRLZXkiOiJGeGhReHljelM0UXFNZVQydzJZY2xlZHA4WFBBd1pQVklHV1JsU3BESzcwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIzNDkwNzg0Mzc4NDRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMjlENTM2QUM4NEQzQ0MyQjY3RUNCMDE3RkVFNzQ5NTMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNzg3NzM5OX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0OTA3ODQzNzg0NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBMEZEQjlFQjEzRkFDNjQ2NDRCMjIyMUU5RDFGN0YzNiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM3ODc3Mzk5fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiI4WjMzWERZQiIsIm1lIjp7ImlkIjoiMjM0OTA3ODQzNzg0NDo4QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkdsaXRjaCIsImxpZCI6IjE0MTMwNDk3NzcyNzU1OTo4QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDS1NFdDdvREVJalAxN3dHR0FNZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiYVZNVCtTSjIwUjlhczFVUmJTN1hFeG4yM3V0UmFiUmc1ZFB3REd5N1FEQT0iLCJhY2NvdW50U2lnbmF0dXJlIjoidjh5blhOVWhEYTByQk5FUW16RDB3VFZpdnVmbVdqMXFCdWFEaGtrc2pzeXpwR0NhSXRaQkN4SVJPNHg3V2Q4akFOR3B2b21yMVUzNm93bjZoNktkQkE9PSIsImRldmljZVNpZ25hdHVyZSI6InFwMXVKZElZczVocXlrTTROQ3VtWHVUR3p1SENIQWh1MlNMUjVxZzY2bWZpUFJUYlpXYTkreDF0MDZlYnRVQ3BJMEZpYUpjUysrVlhrUjdGYWdiTkRnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0OTA3ODQzNzg0NDo4QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQldsVEUva2lkdEVmV3JOVkVXMHUxeE1aOXQ3clVXbTBZT1hUOEF4c3UwQXcifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlEUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNzg3NzM5NiwibGFzdFByb3BIYXNoIjoiMkc0QW11IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFDY2cifQ==",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
