const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Glitch",
    ownerNumber: process.env.OWNER_NUMBER || "2349078437844",
    mode: process.env.MODE || "private",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "false",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "false",
    autoReact: process.env.AUTO_REACT === "false",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0ZOM2haNjZwTVU4TE9iOFJEelBrNnpMZnduZHRYMlhkSlkvdzA3OFkybz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOHZQRWFsbjI4K092QzlVV3VhZWR0NkFPcWdwZlVmUjk1elBpTm5IdGJVRT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0RjdSR1NPSllWR2p5bTFqRXN5VFpzc2t6K2o1WkdhN2ZEYTR3WENFd1VFPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ4KzA4M0MwOVVSQUVlYXRMd3dCM1RpNi9OL3MwYk01RFhPNmtHT1VwbHc4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVMMFo2YitCa3N3anQvbmV0WGdCUHhRSHpIWExCZ0RYNHI3a0hFa1oyVTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InpqaUhqQ2Q2RHNSYnErYnEyK2RIN1dDc0FMUnNpN3dGSXNMYXpLOXVtbUU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUFmM2x6WEVUcWFxcGdSWk1vaEZTSWVoSVJ1bDhZQmhpZlArZC9pUXRIcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiL0U1T2tzZ2k3cCtpWUhvMEtrTk9iVlovc1ZqK3dxWkc5SDBsUHo4cU4xND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdvNnF1Zld4R0ZTVml3RURvSDBZZmNlODkyYTUwS3hrM0hzaytuVS9paXhhZ280MlAwOUpBY0Jwd20wa0o3M2VJbm5iV1N4SHJkZDIreHlQSVBtbERRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTUzLCJhZHZTZWNyZXRLZXkiOiJHM2xJcjJRbnpDU1hjNzNOdVIrVi9LUitSeXJNZmZPQktSTngzYUpNUHdrPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIzNDkwNzg0Mzc4NDRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNjhBMjIzODE3NkU1RTdDRTEyNTMxRUI2RENERjBGMEQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0MDMyMjg1NX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0OTA3ODQzNzg0NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIwMzNDRDE1ODFDQzkyNzI0M0U4OEE1OEQ3NjgwRjEzMyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQwMzIyODU2fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJKSjk3QkFBNiIsIm1lIjp7ImlkIjoiMjM0OTA3ODQzNzg0NDoxMUBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJHbGl0Y2giLCJsaWQiOiIxNDEzMDQ5Nzc3Mjc1NTk6MTFAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKNk1oWjhIRUpYdzdMMEdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJlSnJmUEIyT0Z2VmEvdWpWbFFMNkMrWUZvL2hIUXV2WVV2WGpHVEFQRER3PSIsImFjY291bnRTaWduYXR1cmUiOiJURk0rUHhZdlVEOS9JYTNEWEJxb2RLQmgxOW42NXJNeGNtSlVhSWJhbEIvMkcwWTZYV3pPclVOVDNTOXFlWXI5U0wyb3lCdmdCRy94Nms0TkpqRm9Ddz09IiwiZGV2aWNlU2lnbmF0dXJlIjoibGhJWHBJcnp2c2NHbTVxdy92d3VrcFFiTTF5ZS9QWGlkc2JtZ0dYM1lSY1RjVSt2dzdselNmbDgxaG1zQU1JanY2dUNhSVpQU1YzczAzc3NjV240Q2c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ5MDc4NDM3ODQ0OjExQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlhpYTN6d2RqaGIxV3Y3bzFaVUMrZ3ZtQmFQNFIwTHIyRkwxNHhrd0R3dzgifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlEUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0MDMyMjg1MSwibGFzdFByb3BIYXNoIjoiMkc0QW11IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFNeTMifQ==",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
